import {
  BusinessSettings,
  Category,
  Customer,
  Expense,
  LedgerEntry,
  Payment,
  Product,
  Purchase,
  Sale,
  StockMovement,
  Supplier,
  User,
} from '../types';

export const initialSettings: BusinessSettings = {
  id: 'biz_01',
  name: 'Al-Rehman General Store',
  urduName: 'الرحمٰن جنرل اسٹور اینڈ کریانہ',
  tagline: 'Wholesale & Retail Fast Moving Consumer Goods',
  phone: '0300-8421905 / 042-35892211',
  email: 'accounts@alrehmangeneral.pk',
  address: 'Shop # 14-16, Commercial Market, Block C, Lahore',
  taxNumber: 'NTN: 4182904-8 / STRN: 32778761',
  currency: 'PKR',
  currencySymbol: 'PKR',
  invoicePrefix: 'INV-',
  receiptFooter: 'Thank you for shopping with us! No cash refund. Exchange within 7 days with valid receipt.',
  receiptUrduFooter: 'تشریف آوری کا شکریہ! خریدا گیا مال رسید کے ساتھ 7 دن میں تبدیل کیا جا سکتا ہے۔',
  lowStockThreshold: 15,
  enableTax: false,
  taxRate: 0,
  thermalPaperSize: '80mm',
};

export const initialUsers: User[] = [
  {
    id: 'usr_admin',
    name: 'Muhammad Usman (Admin 1)',
    email: 'admin1@bizledger.pk',
    phone: '0300-8421905',
    role: 'admin',
    active: true,
    designation: 'Managing Partner / Primary Admin',
    adminNumber: 1,
  },
  {
    id: 'usr_admin_2',
    name: 'Zubair Ahmed (Admin 2)',
    email: 'admin2@bizledger.pk',
    phone: '0301-5544332',
    role: 'admin',
    active: true,
    designation: 'Co-Owner / Operations Admin',
    adminNumber: 2,
  },
];

export const initialCategories: Category[] = [
  { id: 'cat_beverages', name: 'Beverages & Drinks', urduName: 'مشروبات', color: 'blue' },
  { id: 'cat_grocery', name: 'Groceries & Spices', urduName: 'کریانہ و مصالحہ جات', color: 'emerald' },
  { id: 'cat_laundry', name: 'Household & Laundry', urduName: 'گھریلو اشیاء و واشنگ', color: 'indigo' },
  { id: 'cat_personal', name: 'Personal Care & Hygiene', urduName: 'پرسنل کیئر', color: 'purple' },
  { id: 'cat_dairy', name: 'Dairy & Bakery', urduName: 'دودھ و بیکری', color: 'amber' },
  { id: 'cat_tea', name: 'Tea & Coffee', urduName: 'چائے و قہوہ', color: 'rose' },
];

export const initialProducts: Product[] = [
  {
    id: 'prod_coke_500',
    name: 'Coca Cola 500ml',
    urduName: 'کوکا کولا 500 ملی لیٹر',
    sku: 'CC-500',
    barcode: '8964000101',
    categoryId: 'cat_beverages',
    brand: 'Coca Cola',
    purchasePrice: 70,
    sellingPrice: 100,
    wholesalePrice: 92,
    currentStock: 100,
    minStock: 25,
    unit: 'Piece',
    description: 'Refreshing cold beverage bottle 500ml',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=300&auto=format&fit=crop&q=60',
    status: 'active',
    totalSold: 240,
  },
  {
    id: 'prod_pepsi_500',
    name: 'Pepsi 500ml',
    urduName: 'پیپسی 500 ملی لیٹر',
    sku: 'PEP-500',
    barcode: '8964000102',
    categoryId: 'cat_beverages',
    brand: 'PepsiCo',
    purchasePrice: 70,
    sellingPrice: 100,
    wholesalePrice: 92,
    currentStock: 80,
    minStock: 20,
    unit: 'Piece',
    description: 'Pepsi Cola chilled pet bottle 500ml',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=300&auto=format&fit=crop&q=60',
    status: 'active',
    totalSold: 190,
  },
  {
    id: 'prod_nestle_15',
    name: 'Nestle Water 1.5L',
    urduName: 'نیسلے منرل واٹر 1.5 لیٹر',
    sku: 'NES-15L',
    barcode: '8964000103',
    categoryId: 'cat_beverages',
    brand: 'Nestle Pure Life',
    purchasePrice: 85,
    sellingPrice: 120,
    wholesalePrice: 110,
    currentStock: 60,
    minStock: 15,
    unit: 'Piece',
    description: 'Purified drinking mineral water 1.5L',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=300&auto=format&fit=crop&q=60',
    status: 'active',
    totalSold: 310,
  },
  {
    id: 'prod_surf_excel',
    name: 'Surf Excel Washing Powder 1kg',
    urduName: 'سرف ایکسل 1 کلو گرام',
    sku: 'SRF-EXC',
    barcode: '8964000104',
    categoryId: 'cat_laundry',
    brand: 'Unilever',
    purchasePrice: 420,
    sellingPrice: 490,
    wholesalePrice: 460,
    currentStock: 45,
    minStock: 12,
    unit: 'Pack',
    description: 'Quick stain removal detergent powder 1kg',
    imageUrl: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=300&auto=format&fit=crop&q=60',
    status: 'active',
    totalSold: 85,
  },
  {
    id: 'prod_lux_soap',
    name: 'Lux Rose Soap 140g',
    urduName: 'لکس صابن 140 گرام',
    sku: 'LUX-SOP',
    barcode: '8964000105',
    categoryId: 'cat_personal',
    brand: 'Lux',
    purchasePrice: 115,
    sellingPrice: 140,
    wholesalePrice: 130,
    currentStock: 90,
    minStock: 20,
    unit: 'Piece',
    description: 'Fragrant beauty bath soap bar 140g',
    imageUrl: 'https://images.unsplash.com/photo-1607006314180-35368a55923b?w=300&auto=format&fit=crop&q=60',
    status: 'active',
    totalSold: 215,
  },
  {
    id: 'prod_shan_biryani',
    name: 'Shan Biryani Masala 50g',
    urduName: 'شان بریانی مصالحہ 50 گرام',
    sku: 'SHN-BIRY',
    barcode: '8964000106',
    categoryId: 'cat_grocery',
    brand: 'Shan Foods',
    purchasePrice: 110,
    sellingPrice: 145,
    wholesalePrice: 135,
    currentStock: 120,
    minStock: 30,
    unit: 'Pack',
    description: 'Authentic Bombay & Sindhi Biryani spice mix',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=300&auto=format&fit=crop&q=60',
    status: 'active',
    totalSold: 340,
  },
  {
    id: 'prod_national_tea',
    name: 'National Tea Bag Box 100s',
    urduName: 'نیشنل ٹی بیگز 100 عدد',
    sku: 'NAT-TEA',
    barcode: '8964000107',
    categoryId: 'cat_tea',
    brand: 'National',
    purchasePrice: 480,
    sellingPrice: 580,
    wholesalePrice: 540,
    currentStock: 35,
    minStock: 10,
    unit: 'Box',
    description: 'Rich blend tea bags carton',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=300&auto=format&fit=crop&q=60',
    status: 'active',
    totalSold: 65,
  },
  {
    id: 'prod_milk_pack_1l',
    name: 'Milk Pak 1L UHT Milk',
    urduName: 'نیسلے ملک پیک 1 لیٹر',
    sku: 'MLK-1L',
    barcode: '8964000108',
    categoryId: 'cat_dairy',
    brand: 'Nestle',
    purchasePrice: 240,
    sellingPrice: 280,
    wholesalePrice: 265,
    currentStock: 11, // low stock alert! (threshold: 15)
    minStock: 15,
    unit: 'Pack',
    description: 'Pure UHT standardized dairy milk 1 Litre',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&auto=format&fit=crop&q=60',
    status: 'active',
    totalSold: 420,
  },
  {
    id: 'prod_tapal_danedar',
    name: 'Tapal Danedar Tea 950g',
    urduName: 'تاپال دانے دار چائے 950 گرام',
    sku: 'TPL-950',
    barcode: '8964000109',
    categoryId: 'cat_tea',
    brand: 'Tapal',
    purchasePrice: 1250,
    sellingPrice: 1450,
    wholesalePrice: 1380,
    currentStock: 25,
    minStock: 10,
    unit: 'Pack',
    description: 'Premium Danedar black tea family pack 950g',
    imageUrl: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=300&auto=format&fit=crop&q=60',
    status: 'active',
    totalSold: 78,
  },
  {
    id: 'prod_dalda_oil',
    name: 'Dalda Cooking Oil 5L',
    urduName: 'ڈالڈا کوکنگ آئل 5 لیٹر کین',
    sku: 'DLD-5L',
    barcode: '8964000110',
    categoryId: 'cat_grocery',
    brand: 'Dalda',
    purchasePrice: 2600,
    sellingPrice: 2950,
    wholesalePrice: 2820,
    currentStock: 8, // Low stock alert!
    minStock: 12,
    unit: 'Piece',
    description: 'Refined pure cooking oil with Vitamin A & D 5 Litres',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&auto=format&fit=crop&q=60',
    status: 'active',
    totalSold: 42,
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust_walkin',
    name: 'Walk-in Customer',
    urduName: 'عام گاہک (نقد)',
    phone: '-',
    address: 'Counter Sale',
    type: 'walk-in',
    openingBalance: 0,
    creditLimit: 0,
    notes: 'Standard cash retail customers',
    currentBalance: 0,
    createdAt: '2026-08-01',
  },
  {
    id: 'cust_ahmed',
    name: 'Ahmed Traders',
    urduName: 'احمد ٹریڈرز (حاجی احمد)',
    phone: '0300-4567891',
    address: 'Shop 12, Anarkali Commercial Center, Lahore',
    email: 'ahmed.traders.lhr@gmail.com',
    type: 'wholesale',
    openingBalance: 5000,
    creditLimit: 50000,
    notes: 'Reliable weekly wholesale customer, payments via JazzCash & Cash',
    currentBalance: 10000, // 5000 opening + 10,000 invoice - 5,000 payment = 10,000
    createdAt: '2026-08-10',
  },
  {
    id: 'cust_ali',
    name: 'Ali General Store',
    urduName: 'علی جنرل اسٹور',
    phone: '0321-9876543',
    address: 'Near Jamia Masjid, Tariq Road, Karachi',
    email: 'aligeneral.khi@yahoo.com',
    type: 'regular',
    openingBalance: 12000,
    creditLimit: 80000,
    notes: 'Bi-weekly billing cycle',
    currentBalance: 15400,
    createdAt: '2026-08-15',
  },
  {
    id: 'cust_bilal',
    name: 'Bilal Bhai (Neighbourhood)',
    urduName: 'بلال بھائی محلہ دار',
    phone: '0333-5551234',
    address: 'House 42, St 5, Sector C, Lahore',
    type: 'regular',
    openingBalance: 2500,
    creditLimit: 15000,
    notes: 'Monthly grocery udhaar account',
    currentBalance: 3950,
    createdAt: '2026-08-20',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'supp_abc',
    name: 'ABC Wholesale & Dist.',
    phone: '0312-3456789',
    address: 'Gate 4, Akbari Mandi Wholesale Market, Lahore',
    email: 'abc.distributors.lhr@gmail.com',
    openingBalance: 45000,
    notes: 'Main distributor for beverages and confectionery',
    currentBalance: 75000, // We owe them ₨75,000
    createdAt: '2026-07-01',
  },
  {
    id: 'supp_karachi',
    name: 'Karachi Distributors',
    phone: '0302-8889990',
    address: 'Jodia Bazaar, Wholesale Hub, Karachi',
    email: 'karachi.dist@pakbiz.pk',
    openingBalance: 80000,
    notes: 'Supplies soaps, detergent & toiletries',
    currentBalance: 52000,
    createdAt: '2026-07-10',
  },
  {
    id: 'supp_national',
    name: 'National Foods & Spices Agency',
    phone: '0345-1237890',
    address: 'Plot 22-B, Industrial Estate, Multan Road, Lahore',
    email: 'supply@nationalagency.pk',
    openingBalance: 30000,
    notes: 'Direct agency for spices, recipe mixes, teas',
    currentBalance: 30000,
    createdAt: '2026-07-20',
  },
];

// Initial ledger entries demonstrating real accounting logic
export const initialCustomerLedger: LedgerEntry[] = [
  {
    id: 'c_led_01',
    partyType: 'customer',
    partyId: 'cust_ahmed',
    partyName: 'Ahmed Traders',
    date: '01-09-2026',
    timestamp: new Date('2026-09-01T09:00:00Z').getTime(),
    reference: 'OPENING',
    description: 'Opening Balance (سابقہ بقایا)',
    debit: 5000,
    credit: 0,
    balance: 5000,
    createdBy: 'Muhammad Usman',
  },
  {
    id: 'c_led_02',
    partyType: 'customer',
    partyId: 'cust_ahmed',
    partyName: 'Ahmed Traders',
    date: '05-09-2026',
    timestamp: new Date('2026-09-05T14:30:00Z').getTime(),
    reference: 'INV-1005',
    description: 'Credit Sale Invoice #INV-1005',
    debit: 10000,
    credit: 0,
    balance: 15000,
    createdBy: 'Hamza Farooq',
  },
  {
    id: 'c_led_03',
    partyType: 'customer',
    partyId: 'cust_ahmed',
    partyName: 'Ahmed Traders',
    date: '07-09-2026',
    timestamp: new Date('2026-09-07T11:15:00Z').getTime(),
    reference: 'PAY-1002',
    description: 'Customer Payment Received via JazzCash (وصولی)',
    debit: 0,
    credit: 5000,
    balance: 10000,
    createdBy: 'Tariq Mehmood',
  },
  {
    id: 'c_led_04',
    partyType: 'customer',
    partyId: 'cust_ali',
    partyName: 'Ali General Store',
    date: '01-09-2026',
    timestamp: new Date('2026-09-01T09:00:00Z').getTime(),
    reference: 'OPENING',
    description: 'Opening Balance (سابقہ بقایا)',
    debit: 12000,
    credit: 0,
    balance: 12000,
    createdBy: 'Muhammad Usman',
  },
  {
    id: 'c_led_05',
    partyType: 'customer',
    partyId: 'cust_ali',
    partyName: 'Ali General Store',
    date: '12-09-2026',
    timestamp: new Date('2026-09-12T16:00:00Z').getTime(),
    reference: 'INV-1012',
    description: 'Credit Sale Invoice #INV-1012',
    debit: 8400,
    credit: 0,
    balance: 20400,
    createdBy: 'Hamza Farooq',
  },
  {
    id: 'c_led_06',
    partyType: 'customer',
    partyId: 'cust_ali',
    partyName: 'Ali General Store',
    date: '18-09-2026',
    timestamp: new Date('2026-09-18T10:30:00Z').getTime(),
    reference: 'PAY-1008',
    description: 'Bank Transfer Payment via HBL (وصولی)',
    debit: 0,
    credit: 5000,
    balance: 15400,
    createdBy: 'Tariq Mehmood',
  },
  {
    id: 'c_led_07',
    partyType: 'customer',
    partyId: 'cust_bilal',
    partyName: 'Bilal Bhai',
    date: '01-09-2026',
    timestamp: new Date('2026-09-01T09:00:00Z').getTime(),
    reference: 'OPENING',
    description: 'Opening Balance (سابقہ ادھار)',
    debit: 2500,
    credit: 0,
    balance: 2500,
    createdBy: 'Muhammad Usman',
  },
  {
    id: 'c_led_08',
    partyType: 'customer',
    partyId: 'cust_bilal',
    partyName: 'Bilal Bhai',
    date: '20-09-2026',
    timestamp: new Date('2026-09-20T19:40:00Z').getTime(),
    reference: 'INV-1018',
    description: 'Daily Groceries on Credit #INV-1018',
    debit: 1450,
    credit: 0,
    balance: 3950,
    createdBy: 'Hamza Farooq',
  },
];

export const initialSupplierLedger: LedgerEntry[] = [
  {
    id: 's_led_01',
    partyType: 'supplier',
    partyId: 'supp_abc',
    partyName: 'ABC Wholesale & Dist.',
    date: '01-09-2026',
    timestamp: new Date('2026-09-01T09:00:00Z').getTime(),
    reference: 'OPENING',
    description: 'Opening Balance Payable (سابقہ واجب الادا)',
    debit: 0,
    credit: 45000,
    balance: 45000,
    createdBy: 'Muhammad Usman',
  },
  {
    id: 's_led_02',
    partyType: 'supplier',
    partyId: 'supp_abc',
    partyName: 'ABC Wholesale & Dist.',
    date: '08-09-2026',
    timestamp: new Date('2026-09-08T11:00:00Z').getTime(),
    reference: 'PUR-2001',
    description: 'Beverages Stock Bulk Purchase Credit',
    debit: 0,
    credit: 50000,
    balance: 95000,
    createdBy: 'Tariq Mehmood',
  },
  {
    id: 's_led_03',
    partyType: 'supplier',
    partyId: 'supp_abc',
    partyName: 'ABC Wholesale & Dist.',
    date: '15-09-2026',
    timestamp: new Date('2026-09-15T15:30:00Z').getTime(),
    reference: 'PAY-SUPP-101',
    description: 'Payment made via Bank Transfer (ادائیگی)',
    debit: 20000,
    credit: 0,
    balance: 75000,
    createdBy: 'Muhammad Usman',
  },
  {
    id: 's_led_04',
    partyType: 'supplier',
    partyId: 'supp_karachi',
    partyName: 'Karachi Distributors',
    date: '01-09-2026',
    timestamp: new Date('2026-09-01T09:00:00Z').getTime(),
    reference: 'OPENING',
    description: 'Opening Balance (سابقہ حساب)',
    debit: 0,
    credit: 80000,
    balance: 80000,
    createdBy: 'Muhammad Usman',
  },
  {
    id: 's_led_05',
    partyType: 'supplier',
    partyId: 'supp_karachi',
    partyName: 'Karachi Distributors',
    date: '10-09-2026',
    timestamp: new Date('2026-09-10T12:00:00Z').getTime(),
    reference: 'PAY-SUPP-102',
    description: 'Cheque Payment cleared (ادائیگی)',
    debit: 28000,
    credit: 0,
    balance: 52000,
    createdBy: 'Tariq Mehmood',
  },
];

export const initialSales: Sale[] = [
  {
    id: 'sale_1005',
    invoiceNumber: 'INV-1005',
    date: '05-09-2026',
    timestamp: new Date('2026-09-05T14:30:00Z').getTime(),
    customerId: 'cust_ahmed',
    customerName: 'Ahmed Traders',
    customerPhone: '0300-4567891',
    items: [
      {
        productId: 'prod_coke_500',
        productName: 'Coca Cola 500ml',
        sku: 'CC-500',
        unit: 'Piece',
        quantity: 50,
        unitPrice: 100,
        purchasePrice: 70,
        discount: 0,
        total: 5000,
      },
      {
        productId: 'prod_pepsi_500',
        productName: 'Pepsi 500ml',
        sku: 'PEP-500',
        unit: 'Piece',
        quantity: 50,
        unitPrice: 100,
        purchasePrice: 70,
        discount: 0,
        total: 5000,
      },
    ],
    subtotal: 10000,
    discount: 0,
    tax: 0,
    grandTotal: 10000,
    amountPaid: 0,
    remainingDue: 10000,
    paymentMethod: 'Credit',
    paymentStatus: 'Credit',
    cashierId: 'usr_cashier',
    cashierName: 'Hamza Farooq',
    notes: 'Wholesale order for Friday market',
  },
  {
    id: 'sale_1020',
    invoiceNumber: 'INV-1020',
    date: '24-09-2026',
    timestamp: new Date('2026-09-24T17:15:00Z').getTime(),
    customerId: 'cust_walkin',
    customerName: 'Walk-in Customer',
    items: [
      {
        productId: 'prod_nestle_15',
        productName: 'Nestle Water 1.5L',
        sku: 'NES-15L',
        unit: 'Piece',
        quantity: 2,
        unitPrice: 120,
        purchasePrice: 85,
        discount: 0,
        total: 240,
      },
      {
        productId: 'prod_shan_biryani',
        productName: 'Shan Biryani Masala 50g',
        sku: 'SHN-BIRY',
        unit: 'Pack',
        quantity: 2,
        unitPrice: 145,
        purchasePrice: 110,
        discount: 0,
        total: 290,
      },
      {
        productId: 'prod_lux_soap',
        productName: 'Lux Rose Soap 140g',
        sku: 'LUX-SOP',
        unit: 'Piece',
        quantity: 1,
        unitPrice: 140,
        purchasePrice: 115,
        discount: 0,
        total: 140,
      },
    ],
    subtotal: 670,
    discount: 20,
    tax: 0,
    grandTotal: 650,
    amountPaid: 650,
    remainingDue: 0,
    paymentMethod: 'Cash',
    paymentStatus: 'Paid',
    cashierId: 'usr_cashier',
    cashierName: 'Hamza Farooq',
  },
  {
    id: 'sale_1021',
    invoiceNumber: 'INV-1021',
    date: '25-09-2026',
    timestamp: new Date('2026-09-25T10:10:00Z').getTime(),
    customerId: 'cust_walkin',
    customerName: 'Walk-in Customer',
    items: [
      {
        productId: 'prod_milk_pack_1l',
        productName: 'Milk Pak 1L UHT Milk',
        sku: 'MLK-1L',
        unit: 'Pack',
        quantity: 3,
        unitPrice: 280,
        purchasePrice: 240,
        discount: 0,
        total: 840,
      },
      {
        productId: 'prod_national_tea',
        productName: 'National Tea Bag Box 100s',
        sku: 'NAT-TEA',
        unit: 'Box',
        quantity: 1,
        unitPrice: 580,
        purchasePrice: 480,
        discount: 0,
        total: 580,
      },
    ],
    subtotal: 1420,
    discount: 0,
    tax: 0,
    grandTotal: 1420,
    amountPaid: 1420,
    remainingDue: 0,
    paymentMethod: 'JazzCash',
    paymentStatus: 'Paid',
    cashierId: 'usr_admin',
    cashierName: 'Muhammad Usman',
  },
];

export const initialPurchases: Purchase[] = [
  {
    id: 'pur_2001',
    invoiceNumber: 'PUR-2001',
    supplierInvoiceRef: 'ABC-INV-9921',
    date: '08-09-2026',
    timestamp: new Date('2026-09-08T11:00:00Z').getTime(),
    supplierId: 'supp_abc',
    supplierName: 'ABC Wholesale & Dist.',
    items: [
      {
        productId: 'prod_coke_500',
        productName: 'Coca Cola 500ml',
        quantity: 300,
        purchasePrice: 70,
        total: 21000,
      },
      {
        productId: 'prod_pepsi_500',
        productName: 'Pepsi 500ml',
        quantity: 300,
        purchasePrice: 70,
        total: 21000,
      },
      {
        productId: 'prod_nestle_15',
        productName: 'Nestle Water 1.5L',
        quantity: 100,
        purchasePrice: 80,
        total: 8000,
      },
    ],
    subtotal: 50000,
    discount: 0,
    total: 50000,
    amountPaid: 0,
    remainingPayable: 50000,
    paymentMethod: 'Credit',
    status: 'Credit',
    notes: 'Bulk stock delivery for September',
  },
];

export const initialPayments: Payment[] = [
  {
    id: 'pay_1002',
    paymentNumber: 'PAY-1002',
    date: '07-09-2026',
    timestamp: new Date('2026-09-07T11:15:00Z').getTime(),
    type: 'customer_payment',
    partyId: 'cust_ahmed',
    partyName: 'Ahmed Traders',
    amount: 5000,
    paymentMethod: 'JazzCash',
    reference: 'JC-8839021',
    notes: 'Partial payment against INV-1005',
    createdBy: 'Tariq Mehmood',
  },
  {
    id: 'pay_1008',
    paymentNumber: 'PAY-1008',
    date: '18-09-2026',
    timestamp: new Date('2026-09-18T10:30:00Z').getTime(),
    type: 'customer_payment',
    partyId: 'cust_ali',
    partyName: 'Ali General Store',
    amount: 5000,
    paymentMethod: 'Bank Transfer',
    reference: 'HBL-FT-499102',
    notes: 'Payment received via HBL mobile app',
    createdBy: 'Tariq Mehmood',
  },
  {
    id: 'pay_supp_101',
    paymentNumber: 'PAY-SUPP-101',
    date: '15-09-2026',
    timestamp: new Date('2026-09-15T15:30:00Z').getTime(),
    type: 'supplier_payment',
    partyId: 'supp_abc',
    partyName: 'ABC Wholesale & Dist.',
    amount: 20000,
    paymentMethod: 'Bank Transfer',
    reference: 'Meezan-ONL-12903',
    notes: 'Direct online transfer to distributor',
    createdBy: 'Muhammad Usman',
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp_01',
    expenseNumber: 'EXP-101',
    date: '05-09-2026',
    timestamp: new Date('2026-09-05T12:00:00Z').getTime(),
    category: 'Rent',
    amount: 35000,
    paymentMethod: 'Bank Transfer',
    description: 'Shop rent for September 2026',
    reference: 'RENT-SEP-26',
    recordedBy: 'Muhammad Usman',
  },
  {
    id: 'exp_02',
    expenseNumber: 'EXP-102',
    date: '10-09-2026',
    timestamp: new Date('2026-09-10T14:20:00Z').getTime(),
    category: 'Electricity',
    amount: 14200,
    paymentMethod: 'Easypaisa',
    description: 'LESCO Commercial electricity bill',
    reference: 'LESCO-6482910',
    recordedBy: 'Tariq Mehmood',
  },
  {
    id: 'exp_03',
    expenseNumber: 'EXP-103',
    date: '12-09-2026',
    timestamp: new Date('2026-09-12T16:00:00Z').getTime(),
    category: 'Internet',
    amount: 3500,
    paymentMethod: 'JazzCash',
    description: 'Nayatel fiber broadband monthly bill',
    reference: 'NYT-847291',
    recordedBy: 'Tariq Mehmood',
  },
  {
    id: 'exp_04',
    expenseNumber: 'EXP-104',
    date: '20-09-2026',
    timestamp: new Date('2026-09-20T17:30:00Z').getTime(),
    category: 'Maintenance',
    amount: 2800,
    paymentMethod: 'Cash',
    description: 'Refrigerator display cooling fan repair & service',
    reference: 'CASH-VOUCHER',
    recordedBy: 'Muhammad Usman',
  },
];

export const initialStockMovements: StockMovement[] = [
  {
    id: 'sm_01',
    productId: 'prod_coke_500',
    productName: 'Coca Cola 500ml',
    date: '08-09-2026',
    timestamp: new Date('2026-09-08T11:00:00Z').getTime(),
    type: 'In',
    quantityChange: 300,
    previousStock: 0,
    newStock: 300,
    reason: 'Purchase',
    reference: 'PUR-2001',
    recordedBy: 'Tariq Mehmood',
  },
  {
    id: 'sm_02',
    productId: 'prod_coke_500',
    productName: 'Coca Cola 500ml',
    date: '05-09-2026',
    timestamp: new Date('2026-09-05T14:30:00Z').getTime(),
    type: 'Out',
    quantityChange: -50,
    previousStock: 150,
    newStock: 100,
    reason: 'Sale',
    reference: 'INV-1005',
    recordedBy: 'Hamza Farooq',
  },
];
